version: "3.7"

services:
  postgres:
    image: postgres:13
    network_mode: bridge
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sadrack
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: todolist

  redis:
    image: redis
    network_mode: bridge
    restart: always
    ports:
      - "6379:6379"
